using System.Collections.Generic;

namespace QuinSlate.Ui.Models;

/// <summary>
/// Provides grouped emoji data for the in-app emoji picker.
/// </summary>
public static class EmojiData
{
    /// <summary>
    /// Returns all emoji groups in display order.
    /// </summary>
    public static IReadOnlyList<EmojiGroup> GetGroups()
    {
        return groups;
    }

    /// <summary>
    /// Returns every emoji entry across all groups as a single flat list,
    /// in display order. Used by the picker's search to avoid walking the
    /// grouped structure on every keystroke.
    /// </summary>
    public static IReadOnlyList<EmojiEntry> GetAllEntries()
    {
        return allEntries;
    }

    private static readonly IReadOnlyList<EmojiGroup> groups = new[]
    {
        new EmojiGroup("Smileys", new[]
        {
            new EmojiEntry("😀","grinning face smile happy"),
            new EmojiEntry("😃","grinning face big eyes smile"),
            new EmojiEntry("😄","grinning face smiling eyes happy"),
            new EmojiEntry("😁","beaming face smile grin"),
            new EmojiEntry("😆","grinning squinting face laugh"),
            new EmojiEntry("😅","grinning face sweat nervous"),
            new EmojiEntry("🤣","rolling on floor laughing lol"),
            new EmojiEntry("😂","face tears joy laugh cry"),
            new EmojiEntry("🙂","slightly smiling face"),
            new EmojiEntry("🙃","upside down face silly"),
            new EmojiEntry("😉","winking face"),
            new EmojiEntry("😊","smiling face blush happy"),
            new EmojiEntry("😇","smiling face halo angel"),
            new EmojiEntry("🥰","smiling hearts love adore"),
            new EmojiEntry("😍","heart eyes love"),
            new EmojiEntry("🤩","star struck excited wow"),
            new EmojiEntry("😘","face blowing kiss love"),
            new EmojiEntry("😗","kissing face"),
            new EmojiEntry("😚","kissing face closed eyes"),
            new EmojiEntry("😙","kissing face smiling"),
            new EmojiEntry("🥲","smiling face tear"),
            new EmojiEntry("😋","face savoring food yum"),
            new EmojiEntry("😛","face tongue out"),
            new EmojiEntry("😜","winking face tongue"),
            new EmojiEntry("🤪","zany face crazy"),
            new EmojiEntry("😝","squinting face tongue"),
            new EmojiEntry("🤑","money mouth face"),
            new EmojiEntry("🤗","hugging face warm"),
            new EmojiEntry("🤭","face hand shush"),
            new EmojiEntry("🤫","shushing face quiet"),
            new EmojiEntry("🤔","thinking face ponder"),
            new EmojiEntry("🤐","zipper mouth face silent"),
            new EmojiEntry("🤨","face raised eyebrow suspicious"),
            new EmojiEntry("😐","neutral face expressionless"),
            new EmojiEntry("😑","expressionless face blank"),
            new EmojiEntry("😶","face without mouth silent"),
            new EmojiEntry("😏","smirking face"),
            new EmojiEntry("😒","unamused face"),
            new EmojiEntry("🙄","face rolling eyes"),
            new EmojiEntry("😬","grimacing face awkward"),
            new EmojiEntry("🤥","lying face pinocchio"),
            new EmojiEntry("😌","relieved face calm"),
            new EmojiEntry("😔","pensive face sad"),
            new EmojiEntry("😪","sleepy face tired"),
            new EmojiEntry("🤤","drooling face"),
            new EmojiEntry("😴","sleeping face zzz"),
            new EmojiEntry("😷","face mask sick"),
            new EmojiEntry("🤒","face thermometer sick"),
            new EmojiEntry("🤕","face bandage hurt"),
            new EmojiEntry("🤢","nauseated face sick"),
            new EmojiEntry("🤧","sneezing face"),
            new EmojiEntry("🥵","hot face overheating"),
            new EmojiEntry("🥶","cold face freezing"),
            new EmojiEntry("🥴","woozy face dizzy"),
            new EmojiEntry("😵","dizzy face"),
            new EmojiEntry("💫","dizzy star spinning"),
            new EmojiEntry("🤯","exploding head mind blown"),
            new EmojiEntry("🤠","cowboy hat face"),
            new EmojiEntry("🥳","partying face celebrate"),
            new EmojiEntry("🥸","disguised face incognito"),
            new EmojiEntry("😎","smiling face sunglasses cool"),
            new EmojiEntry("🤓","nerd face glasses"),
            new EmojiEntry("🧐","face monocle curious"),
            new EmojiEntry("😭","loudly crying face sad tears"),
            new EmojiEntry("😤","face steam nose angry"),
            new EmojiEntry("😠","angry face mad"),
            new EmojiEntry("😡","pouting face rage"),
            new EmojiEntry("🤬","face symbols swearing"),
            new EmojiEntry("😱","screaming fear scared"),
            new EmojiEntry("😨","fearful face scared"),
            new EmojiEntry("😰","anxious face sweat worry"),
            new EmojiEntry("😥","sad but relieved face"),
            new EmojiEntry("😓","downcast face sweat"),
            new EmojiEntry("🫠","melting face"),
        }),
        new EmojiGroup("Animals", new[]
        {
            new EmojiEntry("🐶","dog puppy pet"),
            new EmojiEntry("🐱","cat kitten pet"),
            new EmojiEntry("🐭","mouse rodent"),
            new EmojiEntry("🐹","hamster rodent pet"),
            new EmojiEntry("🐰","rabbit bunny"),
            new EmojiEntry("🦊","fox animal"),
            new EmojiEntry("🐻","bear animal"),
            new EmojiEntry("🐼","panda bear"),
            new EmojiEntry("🐨","koala animal"),
            new EmojiEntry("🐯","tiger animal cat"),
            new EmojiEntry("🦁","lion animal"),
            new EmojiEntry("🐮","cow animal farm"),
            new EmojiEntry("🐷","pig animal farm"),
            new EmojiEntry("🐸","frog animal"),
            new EmojiEntry("🐵","monkey animal"),
            new EmojiEntry("🐔","chicken bird farm"),
            new EmojiEntry("🐧","penguin bird"),
            new EmojiEntry("🐦","bird"),
            new EmojiEntry("🦅","eagle bird"),
            new EmojiEntry("🦆","duck bird"),
            new EmojiEntry("🦉","owl bird"),
            new EmojiEntry("🦋","butterfly insect"),
            new EmojiEntry("🐛","bug worm caterpillar"),
            new EmojiEntry("🐌","snail slow"),
            new EmojiEntry("🐞","ladybug insect"),
            new EmojiEntry("🐜","ant insect"),
            new EmojiEntry("🦟","mosquito insect bug"),
            new EmojiEntry("🦗","cricket insect"),
            new EmojiEntry("🦂","scorpion"),
            new EmojiEntry("🐢","turtle reptile slow"),
            new EmojiEntry("🐍","snake reptile"),
            new EmojiEntry("🦎","lizard reptile"),
            new EmojiEntry("🦖","t-rex dinosaur"),
            new EmojiEntry("🦕","sauropod dinosaur"),
            new EmojiEntry("🐙","octopus sea"),
            new EmojiEntry("🦑","squid sea"),
            new EmojiEntry("🦐","shrimp sea"),
            new EmojiEntry("🦞","lobster sea"),
            new EmojiEntry("🦀","crab sea"),
            new EmojiEntry("🐡","blowfish sea"),
            new EmojiEntry("🐠","tropical fish sea"),
            new EmojiEntry("🐟","fish sea"),
            new EmojiEntry("🐬","dolphin sea"),
            new EmojiEntry("🐳","whale sea"),
            new EmojiEntry("🐋","whale sea"),
            new EmojiEntry("🦈","shark sea"),
            new EmojiEntry("🐊","crocodile reptile"),
            new EmojiEntry("🐅","tiger animal"),
            new EmojiEntry("🐆","leopard animal"),
            new EmojiEntry("🦓","zebra animal"),
            new EmojiEntry("🦍","gorilla primate"),
            new EmojiEntry("🦧","orangutan primate"),
            new EmojiEntry("🦣","mammoth extinct"),
            new EmojiEntry("🐘","elephant animal"),
            new EmojiEntry("🦛","hippo animal"),
            new EmojiEntry("🦏","rhinoceros animal"),
            new EmojiEntry("🐪","camel animal desert"),
            new EmojiEntry("🐫","camel two hump"),
            new EmojiEntry("🦒","giraffe animal"),
            new EmojiEntry("🦘","kangaroo animal"),
            new EmojiEntry("🦬","bison animal"),
            new EmojiEntry("🐃","water buffalo animal"),
            new EmojiEntry("🐂","ox animal farm"),
            new EmojiEntry("🐄","cow animal farm"),
            new EmojiEntry("🐎","horse animal"),
            new EmojiEntry("🐖","pig animal farm"),
            new EmojiEntry("🐏","ram sheep animal"),
            new EmojiEntry("🐑","sheep animal"),
            new EmojiEntry("🦙","llama animal"),
            new EmojiEntry("🐐","goat animal"),
            new EmojiEntry("🦌","deer animal"),
            new EmojiEntry("🐕","dog pet"),
            new EmojiEntry("🐩","poodle dog pet"),
            new EmojiEntry("🦮","guide dog"),
            new EmojiEntry("🐈","cat pet"),
        }),
        new EmojiGroup("Food", new[]
        {
            new EmojiEntry("🍏","green apple fruit"),
            new EmojiEntry("🍎","red apple fruit"),
            new EmojiEntry("🍐","pear fruit"),
            new EmojiEntry("🍊","orange tangerine fruit"),
            new EmojiEntry("🍋","lemon fruit"),
            new EmojiEntry("🍌","banana fruit"),
            new EmojiEntry("🍉","watermelon fruit"),
            new EmojiEntry("🍇","grapes fruit"),
            new EmojiEntry("🍓","strawberry fruit"),
            new EmojiEntry("🫐","blueberries fruit"),
            new EmojiEntry("🍈","melon fruit"),
            new EmojiEntry("🍑","peach fruit"),
            new EmojiEntry("🥭","mango fruit"),
            new EmojiEntry("🍍","pineapple fruit tropical"),
            new EmojiEntry("🥥","coconut fruit"),
            new EmojiEntry("🥝","kiwi fruit"),
            new EmojiEntry("🍅","tomato vegetable"),
            new EmojiEntry("🍆","eggplant vegetable"),
            new EmojiEntry("🥑","avocado vegetable"),
            new EmojiEntry("🫑","bell pepper vegetable"),
            new EmojiEntry("🥦","broccoli vegetable"),
            new EmojiEntry("🥬","leafy green vegetable"),
            new EmojiEntry("🥒","cucumber vegetable"),
            new EmojiEntry("🌶","hot pepper spicy"),
            new EmojiEntry("🧄","garlic vegetable"),
            new EmojiEntry("🧅","onion vegetable"),
            new EmojiEntry("🥔","potato vegetable"),
            new EmojiEntry("🍠","roasted sweet potato"),
            new EmojiEntry("🫘","beans legume"),
            new EmojiEntry("🥜","peanuts nuts"),
            new EmojiEntry("🌰","chestnut nut"),
            new EmojiEntry("🍞","bread bakery"),
            new EmojiEntry("🥐","croissant bakery"),
            new EmojiEntry("🥖","baguette bread"),
            new EmojiEntry("🫓","flatbread"),
            new EmojiEntry("🥨","pretzel snack"),
            new EmojiEntry("🧀","cheese dairy"),
            new EmojiEntry("🥚","egg"),
            new EmojiEntry("🍳","cooking egg frying pan"),
            new EmojiEntry("🧈","butter dairy"),
            new EmojiEntry("🥞","pancakes breakfast"),
            new EmojiEntry("🧇","waffle breakfast"),
            new EmojiEntry("🥓","bacon meat"),
            new EmojiEntry("🥩","meat steak"),
            new EmojiEntry("🍗","poultry leg chicken"),
            new EmojiEntry("🍖","meat bone"),
            new EmojiEntry("🌭","hot dog sausage"),
            new EmojiEntry("🍔","burger hamburger fast food"),
            new EmojiEntry("🍟","french fries fast food"),
            new EmojiEntry("🍕","pizza"),
            new EmojiEntry("🫔","tamale food"),
            new EmojiEntry("🥙","stuffed pita food"),
            new EmojiEntry("🧆","falafel food"),
            new EmojiEntry("🌮","taco mexican food"),
            new EmojiEntry("🌯","burrito wrap food"),
            new EmojiEntry("🥗","salad healthy food"),
            new EmojiEntry("🥘","shallow pan food stew"),
            new EmojiEntry("🫕","fondue food"),
            new EmojiEntry("🧂","salt seasoning"),
            new EmojiEntry("🍱","bento box japanese food"),
            new EmojiEntry("🍘","rice cracker japanese"),
            new EmojiEntry("🍙","rice ball japanese"),
            new EmojiEntry("🍚","cooked rice"),
            new EmojiEntry("🍛","curry rice"),
            new EmojiEntry("🍜","noodles ramen soup"),
            new EmojiEntry("🍝","spaghetti pasta"),
            new EmojiEntry("🍢","oden japanese food"),
            new EmojiEntry("🍣","sushi japanese food"),
            new EmojiEntry("🍤","fried shrimp seafood"),
            new EmojiEntry("🍥","fish cake"),
            new EmojiEntry("🥮","moon cake"),
            new EmojiEntry("🍡","dango japanese sweet"),
            new EmojiEntry("🥟","dumpling dim sum"),
            new EmojiEntry("🥠","fortune cookie"),
            new EmojiEntry("🥡","takeout box"),
            new EmojiEntry("🍦","soft ice cream dessert"),
            new EmojiEntry("🍧","shaved ice dessert"),
            new EmojiEntry("🍨","ice cream dessert"),
            new EmojiEntry("🍩","doughnut donut sweet"),
            new EmojiEntry("🍪","cookie sweet biscuit"),
            new EmojiEntry("🎂","birthday cake celebration"),
            new EmojiEntry("🍰","shortcake dessert sweet"),
            new EmojiEntry("🧁","cupcake sweet"),
            new EmojiEntry("🥧","pie dessert"),
            new EmojiEntry("🍫","chocolate bar sweet"),
            new EmojiEntry("🍬","candy sweet"),
            new EmojiEntry("🍭","lollipop candy sweet"),
            new EmojiEntry("🍮","custard dessert"),
            new EmojiEntry("🍯","honey jar"),
            new EmojiEntry("🍷","wine drink alcohol"),
            new EmojiEntry("🍸","cocktail drink alcohol"),
            new EmojiEntry("🍹","tropical drink cocktail"),
            new EmojiEntry("🧉","mate drink"),
            new EmojiEntry("🍺","beer drink alcohol"),
            new EmojiEntry("🍻","clinking beers drink"),
            new EmojiEntry("🥂","champagne glasses celebration"),
            new EmojiEntry("🥃","whiskey tumbler glass drink"),
            new EmojiEntry("🫗","pouring liquid drink"),
            new EmojiEntry("☕","coffee hot drink"),
            new EmojiEntry("🫖","teapot tea drink"),
            new EmojiEntry("🧋","bubble tea boba drink"),
            new EmojiEntry("🍵","teacup tea drink"),
            new EmojiEntry("🧃","juice box drink"),
            new EmojiEntry("🥤","cup straw drink"),
            new EmojiEntry("🧊","ice cube"),
        }),
        new EmojiGroup("Objects", new[]
        {
            new EmojiEntry("📱","mobile phone smartphone"),
            new EmojiEntry("💻","laptop computer"),
            new EmojiEntry("🖥","desktop computer monitor"),
            new EmojiEntry("🖨","printer"),
            new EmojiEntry("⌨","keyboard"),
            new EmojiEntry("🖱","computer mouse"),
            new EmojiEntry("💾","floppy disk storage"),
            new EmojiEntry("💿","optical disc cd"),
            new EmojiEntry("📀","dvd disc"),
            new EmojiEntry("📷","camera photo"),
            new EmojiEntry("📸","camera flash photo"),
            new EmojiEntry("📹","video camera film"),
            new EmojiEntry("🎥","movie camera film"),
            new EmojiEntry("📽","film projector movie"),
            new EmojiEntry("🎞","film frames movie"),
            new EmojiEntry("📞","telephone phone call"),
            new EmojiEntry("☎","telephone phone"),
            new EmojiEntry("📟","pager"),
            new EmojiEntry("📠","fax machine"),
            new EmojiEntry("📺","television tv"),
            new EmojiEntry("📻","radio"),
            new EmojiEntry("🧭","compass navigation"),
            new EmojiEntry("⏰","alarm clock time"),
            new EmojiEntry("⏱","stopwatch time"),
            new EmojiEntry("⏲","timer clock"),
            new EmojiEntry("⏳","hourglass time"),
            new EmojiEntry("⌚","watch time wrist"),
            new EmojiEntry("🕰","mantelpiece clock"),
            new EmojiEntry("⌛","hourglass done"),
            new EmojiEntry("📡","satellite antenna"),
            new EmojiEntry("🔋","battery power"),
            new EmojiEntry("🔌","electric plug power"),
            new EmojiEntry("💡","lightbulb idea"),
            new EmojiEntry("🔦","flashlight torch"),
            new EmojiEntry("🕯","candle light"),
            new EmojiEntry("🪔","lamp diya"),
            new EmojiEntry("🧯","fire extinguisher"),
            new EmojiEntry("🛒","shopping cart"),
            new EmojiEntry("🛍","shopping bags"),
            new EmojiEntry("🎁","gift present"),
            new EmojiEntry("🎀","ribbon bow"),
            new EmojiEntry("🎊","confetti ball party"),
            new EmojiEntry("🎉","party popper celebrate"),
            new EmojiEntry("🎈","balloon party"),
            new EmojiEntry("🎟","admission ticket"),
            new EmojiEntry("🎫","ticket"),
            new EmojiEntry("🏆","trophy winner award"),
            new EmojiEntry("🥇","gold medal first place"),
            new EmojiEntry("🥈","silver medal second"),
            new EmojiEntry("🥉","bronze medal third"),
            new EmojiEntry("🏅","sports medal"),
            new EmojiEntry("🥊","boxing glove sport"),
            new EmojiEntry("🥋","martial arts uniform"),
            new EmojiEntry("🎯","direct hit target"),
            new EmojiEntry("🎱","pool billiards game"),
            new EmojiEntry("🔮","crystal ball magic"),
            new EmojiEntry("🪄","magic wand"),
            new EmojiEntry("🎭","performing arts theater"),
            new EmojiEntry("🎨","artist palette paint"),
            new EmojiEntry("🖼","framed picture art"),
            new EmojiEntry("🎤","microphone sing"),
            new EmojiEntry("🎧","headphone audio music"),
            new EmojiEntry("🎼","musical score notes"),
            new EmojiEntry("🎵","musical note"),
            new EmojiEntry("🎶","musical notes"),
            new EmojiEntry("🎹","piano keyboard music"),
            new EmojiEntry("🎸","guitar music"),
            new EmojiEntry("🎻","violin music"),
            new EmojiEntry("🎺","trumpet music"),
            new EmojiEntry("🥁","drum music"),
            new EmojiEntry("🪘","long drum"),
            new EmojiEntry("📖","open book reading"),
            new EmojiEntry("📚","books library"),
            new EmojiEntry("📰","newspaper news"),
            new EmojiEntry("📑","bookmark tabs"),
            new EmojiEntry("📄","page document"),
            new EmojiEntry("📃","page curl document"),
            new EmojiEntry("📜","scroll document"),
            new EmojiEntry("📋","clipboard"),
            new EmojiEntry("📊","bar chart data"),
            new EmojiEntry("📈","chart increasing graph"),
            new EmojiEntry("📉","chart decreasing graph"),
            new EmojiEntry("🗒","spiral notepad"),
            new EmojiEntry("🗓","spiral calendar"),
            new EmojiEntry("📆","tear-off calendar"),
            new EmojiEntry("📅","calendar"),
            new EmojiEntry("🗑","wastebasket trash"),
            new EmojiEntry("📁","file folder"),
            new EmojiEntry("📂","open file folder"),
            new EmojiEntry("🗂","card index dividers"),
            new EmojiEntry("📌","pushpin location"),
            new EmojiEntry("📍","round pushpin"),
            new EmojiEntry("📎","paperclip"),
            new EmojiEntry("🖇","linked paperclips"),
            new EmojiEntry("📏","straight ruler measure"),
            new EmojiEntry("📐","triangular ruler measure"),
            new EmojiEntry("✂","scissors cut"),
            new EmojiEntry("🖊","pen write"),
            new EmojiEntry("🖋","fountain pen write"),
            new EmojiEntry("✒","black nib pen"),
            new EmojiEntry("🖌","paintbrush art"),
            new EmojiEntry("🖍","crayon draw"),
            new EmojiEntry("📝","memo note write"),
            new EmojiEntry("✏","pencil write"),
            new EmojiEntry("🔍","magnifying glass search left"),
            new EmojiEntry("🔎","magnifying glass search right"),
            new EmojiEntry("🔐","locked key"),
            new EmojiEntry("🔏","locked pen"),
            new EmojiEntry("🔓","unlocked"),
            new EmojiEntry("🔒","locked"),
            new EmojiEntry("🔑","key"),
            new EmojiEntry("🗝","old key"),
            new EmojiEntry("🔨","hammer tool"),
            new EmojiEntry("🪓","axe tool"),
            new EmojiEntry("🪚","carpentry saw tool"),
            new EmojiEntry("🔧","wrench tool"),
            new EmojiEntry("🔩","nut bolt tool"),
            new EmojiEntry("⚙","gear settings"),
            new EmojiEntry("🗜","clamp tool"),
            new EmojiEntry("🪤","mousetrap"),
        }),
        new EmojiGroup("Symbols", new[]
        {
            new EmojiEntry("❤","red heart love"),
            new EmojiEntry("🧡","orange heart love"),
            new EmojiEntry("💛","yellow heart love"),
            new EmojiEntry("💚","green heart love"),
            new EmojiEntry("💙","blue heart love"),
            new EmojiEntry("💜","purple heart love"),
            new EmojiEntry("🖤","black heart love"),
            new EmojiEntry("🤍","white heart love"),
            new EmojiEntry("🤎","brown heart love"),
            new EmojiEntry("💔","broken heart"),
            new EmojiEntry("❣","heart exclamation"),
            new EmojiEntry("💕","two hearts love"),
            new EmojiEntry("💞","revolving hearts love"),
            new EmojiEntry("💓","beating heart love"),
            new EmojiEntry("💗","growing heart love"),
            new EmojiEntry("💖","sparkling heart love"),
            new EmojiEntry("💘","heart arrow love cupid"),
            new EmojiEntry("💝","heart ribbon love"),
            new EmojiEntry("💟","heart decoration love"),
            new EmojiEntry("☮","peace symbol"),
            new EmojiEntry("✝","latin cross religion"),
            new EmojiEntry("☪","star crescent islam"),
            new EmojiEntry("🕉","om hindu"),
            new EmojiEntry("☸","wheel dharma buddhism"),
            new EmojiEntry("✡","star of david jewish"),
            new EmojiEntry("🔯","dotted six pointed star"),
            new EmojiEntry("🕎","menorah jewish"),
            new EmojiEntry("☯","yin yang balance"),
            new EmojiEntry("☦","orthodox cross religion"),
            new EmojiEntry("🛐","place of worship"),
            new EmojiEntry("♻","recycling symbol green"),
            new EmojiEntry("🔱","trident emblem"),
            new EmojiEntry("⚜","fleur de lis"),
            new EmojiEntry("🔰","japanese beginner symbol"),
            new EmojiEntry("✅","check mark button ok"),
            new EmojiEntry("❎","cross mark button"),
            new EmojiEntry("🆗","ok button"),
            new EmojiEntry("🆙","up button"),
            new EmojiEntry("🆒","cool button"),
            new EmojiEntry("🆕","new button"),
            new EmojiEntry("🆓","free button"),
            new EmojiEntry("🔟","keycap ten"),
            new EmojiEntry("🔢","input numbers"),
            new EmojiEntry("🔣","input symbols"),
            new EmojiEntry("🔤","input latin letters"),
            new EmojiEntry("🅰","blood type a"),
            new EmojiEntry("🅱","blood type b"),
            new EmojiEntry("🆎","ab button blood type"),
            new EmojiEntry("🆑","cl button"),
            new EmojiEntry("🅾","blood type o"),
            new EmojiEntry("🆘","sos button emergency"),
            new EmojiEntry("❌","cross mark x error"),
            new EmojiEntry("⭕","hollow red circle"),
            new EmojiEntry("🛑","stop sign"),
            new EmojiEntry("⛔","no entry prohibited"),
            new EmojiEntry("🚫","prohibited banned"),
            new EmojiEntry("🔞","no one under eighteen"),
            new EmojiEntry("📵","no mobile phones"),
            new EmojiEntry("❗","exclamation mark"),
            new EmojiEntry("❕","white exclamation"),
            new EmojiEntry("❓","question mark"),
            new EmojiEntry("❔","white question"),
            new EmojiEntry("‼","double exclamation"),
            new EmojiEntry("⁉","exclamation question"),
            new EmojiEntry("💯","hundred points"),
            new EmojiEntry("🔚","end arrow"),
            new EmojiEntry("🔛","on arrow"),
            new EmojiEntry("🔜","soon arrow"),
            new EmojiEntry("🔝","top arrow"),
            new EmojiEntry("🔙","back arrow"),
            new EmojiEntry("🔇","muted speaker"),
            new EmojiEntry("🔈","speaker low volume"),
            new EmojiEntry("🔉","speaker medium volume"),
            new EmojiEntry("🔊","speaker high volume"),
            new EmojiEntry("📢","loudspeaker"),
            new EmojiEntry("📣","megaphone"),
            new EmojiEntry("🔔","bell notification"),
            new EmojiEntry("🔕","bell with slash muted"),
            new EmojiEntry("🎵","musical note"),
            new EmojiEntry("🎶","musical notes"),
            new EmojiEntry("💬","speech bubble comment"),
            new EmojiEntry("💭","thought balloon think"),
            new EmojiEntry("🗯","anger symbol"),
            new EmojiEntry("⭐","star"),
            new EmojiEntry("🌟","glowing star"),
            new EmojiEntry("💫","dizzy star"),
            new EmojiEntry("✨","sparkles magic"),
            new EmojiEntry("🔥","fire flame hot"),
            new EmojiEntry("💥","collision explosion"),
        }),
        new EmojiGroup("Travel", new[]
        {
            new EmojiEntry("🚗","car automobile"),
            new EmojiEntry("🚕","taxi cab"),
            new EmojiEntry("🚙","suv sport utility vehicle"),
            new EmojiEntry("🚌","bus transport"),
            new EmojiEntry("🚎","trolleybus"),
            new EmojiEntry("🚐","minibus"),
            new EmojiEntry("🚑","ambulance emergency"),
            new EmojiEntry("🚒","fire engine truck"),
            new EmojiEntry("🚓","police car"),
            new EmojiEntry("🚔","police car oncoming"),
            new EmojiEntry("🚖","oncoming taxi"),
            new EmojiEntry("🚡","aerial tramway"),
            new EmojiEntry("🚠","mountain cableway"),
            new EmojiEntry("🚟","suspension railway"),
            new EmojiEntry("🚃","railway car"),
            new EmojiEntry("🚋","tram car"),
            new EmojiEntry("🚞","mountain railway"),
            new EmojiEntry("🚝","monorail"),
            new EmojiEntry("🚄","high-speed train"),
            new EmojiEntry("🚅","bullet train"),
            new EmojiEntry("🚈","light rail"),
            new EmojiEntry("🚂","locomotive steam train"),
            new EmojiEntry("🚆","train"),
            new EmojiEntry("🚇","metro subway"),
            new EmojiEntry("🚊","tram"),
            new EmojiEntry("🚉","station train"),
            new EmojiEntry("✈","airplane plane flight"),
            new EmojiEntry("🛫","airplane departure"),
            new EmojiEntry("🛬","airplane arrival"),
            new EmojiEntry("🛩","small airplane"),
            new EmojiEntry("💺","seat chair"),
            new EmojiEntry("🚀","rocket space"),
            new EmojiEntry("🛸","flying saucer ufo"),
            new EmojiEntry("🚁","helicopter"),
            new EmojiEntry("🪂","parachute"),
            new EmojiEntry("⛵","sailboat water"),
            new EmojiEntry("🚤","speedboat water"),
            new EmojiEntry("🛥","motor boat water"),
            new EmojiEntry("🛳","passenger ship"),
            new EmojiEntry("⛴","ferry boat"),
            new EmojiEntry("🚢","ship cruise"),
            new EmojiEntry("🛶","canoe rowboat"),
            new EmojiEntry("⛽","fuel pump gas station"),
            new EmojiEntry("🚧","construction barrier"),
            new EmojiEntry("🚨","police lights emergency"),
            new EmojiEntry("🚥","horizontal traffic light"),
            new EmojiEntry("🚦","vertical traffic light"),
            new EmojiEntry("🚏","bus stop"),
            new EmojiEntry("🗺","world map"),
            new EmojiEntry("🏔","snow-capped mountain"),
            new EmojiEntry("⛰","mountain"),
            new EmojiEntry("🌋","volcano"),
            new EmojiEntry("🗻","mount fuji japan"),
            new EmojiEntry("🏕","camping tent"),
            new EmojiEntry("🏖","beach umbrella"),
            new EmojiEntry("🏜","desert"),
            new EmojiEntry("🏝","desert island"),
            new EmojiEntry("🏞","national park"),
            new EmojiEntry("🏟","stadium sports"),
            new EmojiEntry("🏛","classical building"),
            new EmojiEntry("🏗","building construction"),
            new EmojiEntry("🧱","brick wall"),
            new EmojiEntry("🏘","houses"),
            new EmojiEntry("🏚","derelict house"),
            new EmojiEntry("🏠","house home"),
            new EmojiEntry("🏡","house garden home"),
            new EmojiEntry("🏢","office building"),
            new EmojiEntry("🏣","japanese post office"),
            new EmojiEntry("🏤","post office"),
            new EmojiEntry("🏥","hospital"),
            new EmojiEntry("🏦","bank"),
            new EmojiEntry("🏨","hotel"),
            new EmojiEntry("🏩","love hotel"),
            new EmojiEntry("🏪","convenience store shop"),
            new EmojiEntry("🏫","school"),
            new EmojiEntry("🏬","department store shop"),
            new EmojiEntry("🏭","factory"),
            new EmojiEntry("🏯","japanese castle"),
            new EmojiEntry("🏰","castle"),
            new EmojiEntry("💒","wedding chapel"),
            new EmojiEntry("🗼","tokyo tower japan"),
            new EmojiEntry("🗽","statue of liberty usa"),
            new EmojiEntry("⛪","church"),
            new EmojiEntry("🕌","mosque"),
            new EmojiEntry("🛕","hindu temple"),
            new EmojiEntry("🕍","synagogue"),
            new EmojiEntry("⛩","shinto shrine japan"),
            new EmojiEntry("🕋","kaaba mecca"),
            new EmojiEntry("⛲","fountain"),
            new EmojiEntry("🌁","foggy"),
        }),
        new EmojiGroup("Activities", new[]
        {
            new EmojiEntry("⚽","soccer football sport"),
            new EmojiEntry("🏀","basketball sport"),
            new EmojiEntry("🏈","american football sport"),
            new EmojiEntry("⚾","baseball sport"),
            new EmojiEntry("🥎","softball sport"),
            new EmojiEntry("🎾","tennis sport"),
            new EmojiEntry("🏐","volleyball sport"),
            new EmojiEntry("🏉","rugby football sport"),
            new EmojiEntry("🥏","flying disc frisbee sport"),
            new EmojiEntry("🎱","pool billiards game"),
            new EmojiEntry("🪃","boomerang"),
            new EmojiEntry("🏓","ping pong table tennis sport"),
            new EmojiEntry("🏸","badminton sport"),
            new EmojiEntry("🏒","ice hockey sport"),
            new EmojiEntry("🏑","field hockey sport"),
            new EmojiEntry("🥍","lacrosse sport"),
            new EmojiEntry("🏏","cricket sport"),
            new EmojiEntry("🪀","yo-yo toy"),
            new EmojiEntry("🎿","skis skiing sport"),
            new EmojiEntry("⛷","skier sport"),
            new EmojiEntry("🏂","snowboarder sport"),
            new EmojiEntry("🪂","parachute skydiving sport"),
            new EmojiEntry("🤺","person fencing sport"),
            new EmojiEntry("⛹","person bouncing ball sport"),
            new EmojiEntry("🤼","people wrestling sport"),
            new EmojiEntry("🤸","person cartwheel gymnastics"),
            new EmojiEntry("🧗","person climbing sport"),
            new EmojiEntry("🚵","mountain biking sport"),
            new EmojiEntry("🏇","horse racing sport"),
            new EmojiEntry("🤾","handball sport"),
            new EmojiEntry("🤽","water polo sport"),
            new EmojiEntry("🧘","yoga meditation"),
            new EmojiEntry("🏋","weightlifting gym sport"),
            new EmojiEntry("🚴","cyclist biking sport"),
            new EmojiEntry("🏊","swimming sport"),
            new EmojiEntry("🏄","surfing sport"),
            new EmojiEntry("🎳","bowling sport"),
            new EmojiEntry("🎯","direct hit bullseye"),
            new EmojiEntry("🎮","video game controller"),
            new EmojiEntry("🎲","game die dice"),
            new EmojiEntry("🎰","slot machine casino"),
            new EmojiEntry("🧩","puzzle piece"),
            new EmojiEntry("♟","chess pawn game"),
            new EmojiEntry("🎭","performing arts theater"),
            new EmojiEntry("🎨","artist palette art paint"),
            new EmojiEntry("🎬","clapper board film movie"),
            new EmojiEntry("🎤","microphone sing performance"),
            new EmojiEntry("🎧","headphones music listen"),
            new EmojiEntry("🎼","musical score"),
            new EmojiEntry("🥁","drum music"),
            new EmojiEntry("🎹","piano keyboard music"),
            new EmojiEntry("🎸","guitar music"),
            new EmojiEntry("🎺","trumpet music"),
            new EmojiEntry("🎻","violin music"),
            new EmojiEntry("🪗","accordion music"),
            new EmojiEntry("🎙","studio microphone"),
            new EmojiEntry("🎚","level slider audio"),
            new EmojiEntry("🎛","control knobs audio"),
            new EmojiEntry("📻","radio music"),
            new EmojiEntry("🏆","trophy winner award"),
            new EmojiEntry("🥇","gold medal"),
            new EmojiEntry("🎖","military medal award"),
            new EmojiEntry("🏅","sports medal"),
            new EmojiEntry("🥈","silver medal"),
            new EmojiEntry("🥉","bronze medal"),
            new EmojiEntry("🎀","ribbon"),
            new EmojiEntry("🎁","gift present"),
            new EmojiEntry("🎊","confetti ball"),
            new EmojiEntry("🎉","party popper celebrate"),
            new EmojiEntry("🎈","balloon"),
            new EmojiEntry("🎟","admission ticket"),
            new EmojiEntry("🎫","ticket"),
            new EmojiEntry("🥂","clinking glasses celebrate"),
            new EmojiEntry("🎗","reminder ribbon"),
        }),
    };

    private static readonly IReadOnlyList<EmojiEntry> allEntries = BuildAllEntries();

    private static IReadOnlyList<EmojiEntry> BuildAllEntries()
    {
        var flat = new List<EmojiEntry>();
        foreach (var group in groups)
        {
            flat.AddRange(group.Entries);
        }

        return flat;
    }
}
